spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
        add-to-simple-url-handler-mapping: true
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8090}
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          predicates:
            - Path=/token
        - id: registration-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8090}
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          predicates:
            - Path=/registration
        - id: job-service
          uri: ${JOB_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - AuthenticationFilter

config:
  job-service-url: ${JOB_SERVICE_URL:http://localhost:8082}
  auth-service-url: ${AUTH_SERVICE_URL:http://localhost:8090}
server:
  port: 8085