spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: auth-service
          uri: http://localhost:8090
          predicates:
            - Path=/token
        - id: registration-service
          uri: http://localhost:8090
          predicates:
            - Path=/registration
        - id: job-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/**
          filters:
            - AuthenticationFilter


server:
  port: 8085